APPLICATION_NAME = "Gazpro"
APPLICATION_SLOGAN = "Application de gestion de gaz"
APPLICATION_DESCRIPTION = ""
APPLICATION_KEYWORDS = [""]

GENDERS = [["Homme"], ["Femme"]]
SEXES = [["Masculin"], ["Féminin"]]
REGISTER_STATUSES = [["Ouvert"], ["Fermé"]]
REGISTER_TYPES = [["Registre arrivée"], ["Registre départ"]]
TASK_STATUSES = [["En attente"], ["En cours"], ["Suspendu"], ["Terminé"], ["Annulé"]]
PRIORITIES = [["Aucun"],["Normal"], ["Basse"], ["Moyenne"], ["Haute"], ["Urgent"]]
TICKET_STATUSES = [["Nouveau"], ["En cours"], ["Résolu"], ["Fermé"], ["Rejeté"], ["En attente"]]
PERMISSION_ACTIONS = [["read"], ["create"], ["update"], ["destroy"]]
DELIVERY_METHOD = [["SMTP"]]
AUTHENTICATION_METHOD = [["Aucune"], ["Plain"], ["TLS"], ["SSL"]]
STORAGE_SERVICES = [["Local"], ["Amazon"], ["Google Cloud"], ["Microsoft Azure"]]
DAYS = [["Lundi"], ["Mardi"], ["Mercredi"], ["Jeudi"], ["Vendredi"], ["Samedi"], ["Dimanche"]]
CURRENCY_SYMBOL_POSITIONS = [["Gauche"] , ["Droite"]]
SENDING_PARCEL_STATUSES = [["Déposé"] , ["Envoyé"],["Arrivé"], ["Retiré"]]
CIVILITIES = [["Mr"], ["Mme"], ["Mlle"]]